### ISSUE TITLE
[ASHWINI] [ASHWINI not to inherit from org 1]

### ISSUE THREAD

**Issue by nupoorkhandelwal** [OpenCHS/ashwini#25]
Tasks--

Download bundle from ashwini and make following changes-- 

1. Add org1 concepts( only those which are used in ashwini) to the bundle
  -- Concepts used in ashwini2 and already present in the org1 **Done**
   --Individual Registration concepts **Done**
    --Mother concepts **Done**
   --Child concepts  **Done**
   -- Vaccination concepts**Done**

2. Copied subject type "Individual" **Done**
   Porgram "Mother","Child"  **Done**
  
  Encounter types "Delivery","ANC","PNC",Abortion" **Done**
                             "Birth form", "Child PNC", "Anthropommetry assessment" **Done**
  Form mappings-- CHild and mother forms  **Done**

2. Forms from org 1 --
 Mother Enrollment, **Done** addition and deletions
 ANC,  **Done** addition and deletions
 Delivery,  **Done** addition deletions
 Abortion,  **Done**
 PNC **Done**
 Exit **Done**
 Child Enrollment **Done**
 Birth Form **Done**
 Anthropometry assessment **Done**
 Checklist  ( Added rule and not the checklist.json, so it wont work on UAT) **Done**
   to the bundle

3. Create a new org  ASHWINI UAT  and  upload bundle to ashwini UAT **Done**

3. Add rules from  org 1 (View Filter, Decision rules for enrollment and encounters and Visit scheduling for mother and child programs ) and  (Checklist Vaccination rule) to new org 

-- View filter rules for Mother  **Done**
-- View filter rules for Child  **Done**
-- Decision rules for Mother  **Done**
-- Decision rules for Child **Done**

-- Program summary rule for Mother 
-- Program summary rule for Child

**Comment by nupoorkhandelwal** [comment]
Estimate - 2 day

@garimadosar5  I have created a user qauser@ashwiniuat, u can test using this.

**Comment by garimadosar5** [comment]
QA Notes - 
- In the child module, Vaccination list is not there. Check if that was there. --**Fixed**
- Also, for child and mother module there is enrolment eligibility rule. So for child `mother` program is not seen. So `Family Planning` module should also not be seen. - Please check once.-- **Will ask Kannan to check that.If they need ,he can add by himself.**
