### ISSUE TITLE
[Ashwini Support] Add the missing type of form elements 

### ISSUE THREAD

**Issue by nupoorkhandelwal** [OpenCHS/ashwini#38]
In Ashwini Prod organisation, around 303 coded form elements have missing type in db while this information is somehow present on App designer. We need to add these missing values as ETL is not working without these values.

Support ticket - https://avni.freshdesk.com/a/tickets/3091

Query used to find these elements -

```

set role ashwini;
select * from form_element fe
inner join concept c on fe.concept_id = c.id
where c.data_type = 'Coded' and fe.type is null;
```

Now, since Kannan has provided us with this information, please update the same in DB -

https://docs.google.com/spreadsheets/d/1KlSnyJMYJ2LBs6_MhSKlwYdHbfR7mWb04JfLvfqZbYI/edit#gid=1568604557

- [x] Write a script to add the type to these coded form elements
- [x] Make sure the ETL is working post this update.

**Comment by Gojo-Taqi** [comment]
[Script to update types for formElements.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzhKQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73278875c2ddb83106af70b8a694b96bce4c4773/Script%20to%20update%20types%20for%20formElements.txt)
Have added the script file above

**Comment by sachsk** [comment]
@Gojo-Taqi add last_modified_date as current_timestamp + ((id % 4000) * interval '1 millisecond')
