### ISSUE TITLE
[RFT] undefined is not an object (evaluating 'imports.motherCalculations.gestationalAgeCategoryAsOn')

### ISSUE THREAD

**Issue by arjunk** [OpenCHS/ashwini#39]
Rule UUID/Source id : cc6a3c6a-c3cc-488d-a46c-d9d538fcc9c2
Rule : Program Encounter Decision
Current count : 15

[Metabase report link](https://reporting.avniproject.org/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6ImNhcmRfXzU0MiIsImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZCIsIm9yZ2FuaXNhdGlvbiIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sIkFzaHdpbmkiXSxbIj0iLFsiZmllbGQiLCJydWxlX3V1aWQiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLCJjYzZhM2M2YS1jM2NjLTQ4OGQtYTQ2Yy1kOWQ1MzhmY2M5YzIiXV19LCJ0eXBlIjoicXVlcnkiLCJkYXRhYmFzZSI6NX0sImRpc3BsYXkiOiJ0YWJsZSIsImRpc3BsYXlJc0xvY2tlZCI6dHJ1ZSwicGFyYW1ldGVycyI6bnVsbCwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJwaXZvdF90YWJsZS5jb2x1bW5fc3BsaXQiOnsicm93cyI6W1siZmllbGQiLCJvcmdhbmlzYXRpb24iLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLFsiZmllbGQiLCJydWxlX3V1aWQiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dXSwiY29sdW1ucyI6W10sInZhbHVlcyI6W1siYWdncmVnYXRpb24iLDBdXX0sInBpdm90X3RhYmxlLmNvbGxhcHNlZF9yb3dzIjp7InZhbHVlIjpbIltcIkpTU0NQXCJdIiwiW1wiSUhNUFwiXSIsIltcIkFQRiBPZGlzaGFcIl0iLCJbXCJKTlBDVFwiXSIsIltcIkpTUyBTaW5ncmF1bGlcIl0iLCJbXCJMZW5kLWEtaGFuZC1pbmRpYSBVQVRcIl0iLCJbXCJMZW5kIGEgSGFuZCBJbmRpYVwiXSIsIltcIklQSCBNREFUIFRyaWFsXCJdIiwiW1wiSUhNUCBUUkFJTklOR1wiXSIsIltcIlNha2hpIEFwcFwiXSIsIltcIlBvV0VSXCJdIl0sInJvd3MiOltbImZpZWxkIiwib3JnYW5pc2F0aW9uIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSxbImZpZWxkIiwicnVsZV91dWlkIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XV19fSwib3JpZ2luYWxfY2FyZF9pZCI6MjcyM30=)

**Comment by BEULAHEVANJALIN** [comment]
```sql
update rule_failure_telemetry
set is_closed        = true,
    closed_date_time = current_timestamp
where rule_uuid = 'cc6a3c6a-c3cc-488d-a46c-d9d538fcc9c2'
  and is_closed is false
  and organisation_id = (select id from organisation where name = 'Ashwini');
```

Closed 32 rfts.
